### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by sfm-user-1** [RuojinCai/doppelgangers#10]
Hi, thanks for your work and for sharing the code. I noticed that some of the docstrings don't agree with the function signatures, e.g. an extra `df` argument

https://github.com/RuojinCai/doppelgangers/blob/43d9eb06f89d882a288644983f877467b741c2f9/doppelgangers/utils/dataset.py#L47

or missing docstrings, e.g. https://github.com/RuojinCai/doppelgangers/blob/main/doppelgangers/utils/loftr_matches.py#L31

Would it be possible to upgrade the code quality, by adding type annotations and docstrings to each function, by formatting the code with a code formatter such as python black, and using a style guide such as Google style guide? (https://google.github.io/styleguide/pyguide.html)

**Comment by RuojinCai** [comment]
Hello, thank you for your feedback! The code you mentioned includes some adaptations from the LoFTR codebase (reference: [LoFTR](https://github.com/zju3dv/LoFTR/blob/df7ca80f917334b94cfbe32cc2901e09a80e70a8/src/datasets/megadepth.py#L33C13-L33C122)), and the `df` argument refers to the division factor (df stands for "division factor", an optional integer that adjusts the image size after resizing). We appreciate your suggestion and will work on improving the code quality.
