### ISSUE TITLE
How can I view the rendering effect of reconstructions.tar.gz

### ISSUE THREAD

**Issue by mzsh-666** [RuojinCai/doppelgangers#12]

**Comment by jot-jt** [comment]
Hello! You can view the reconstructions using the COLMAP GUI.
Here are some helpful links:

- Installation instructions for COLMAP: [here](https://colmap.github.io/install.html)
- Some more information on the GUI: [here](https://colmap.github.io/gui.html)
- Model import instructions: [here](https://colmap.github.io/format.html#sparse-reconstruction)

In the GUI, you can render the reconstruction using `File > Import Model`. Then select a folder that contains `cameras.bin`, `images.bin`, and `points3d.bin`, such as `alexander_nevsky_cathedral/colmap/0`.
