### ISSUE TITLE
Requires vocab tree trained weights?

### ISSUE THREAD

**Issue by abrahamezzeddine** [RuojinCai/doppelgangers#15]
Hello,

Thank you for creating such a software. I appreciate your time a lot. Thanks!

**1.**  I am executing the command and putting in the files in their associated directories, however, I run into an error as the code expect vocab_tree_flickr100K_words1M.bin to be in weights as well.

[Vocabulary tree with 32K visual words](https://demuc.de/colmap/vocab_tree_flickr100K_words32K.bin)
(for small-scale image collections, i.e. 100s to 1,000s of images)
[Vocabulary tree with 256K visual words](https://demuc.de/colmap/vocab_tree_flickr100K_words256K.bin)
(for medium-scale image collections, i.e. 1,000s to 10,000s of images)
[Vocabulary tree with 1M visual words](https://demuc.de/colmap/vocab_tree_flickr100K_words1M.bin)
(for large-scale image collections, i.e. 10,000s - 100,000s of images)

Depending on the amount of images, you have to use different vocab trees for this, but seems hardcoded to use the 1M vocab tree.

Have I missed anything?

Vocabulary tree feature matching
==============================================================================
F20240515 10:57:15.526295  1452 visual_index.h:569] Check failed: file.is_open() weights/vocab_tree_flickr100K_words1M.bin
*** Check failure stack trace: ***
    @   00007FF9333C752A  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FF9333C5BF9  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF631434032  (unknown)
    @   00007FF6314611C2  (unknown)
    @   00007FF6314EC650  (unknown)
    @   00007FF6314EADBF  (unknown)
    @   00007FF9D5689333  _recalloc
    @   00007FF9D675257D  BaseThreadInitThunk
    @   00007FF9D7AAAA48  RtlUserThreadStart
Extracting loftr matches
Traceback (most recent call last):
  File "script_sfm_disambiguation.py", line 237, in <module>
    main()
  File "script_sfm_disambiguation.py", line 233, in main
    main_worker(args.gpu, ngpus_per_node, cfg, args)
  File "script_sfm_disambiguation.py", line 179, in main_worker
    pair_path = create_image_pair_list(args.database_path, args.output_path)
  File "C:\Gaussian\doppelgangers-main\doppelgangers\utils\process_database.py", line 69, in create_image_pair_list
    pairs_list = np.concatenate(pairs_list, axis=0).reshape(-1, 5)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

When downloading and putting that file, it worked to index the files correctly.

2. **In addition to that, the pytorch that is in the environment file does not support cuda 10.2 anymore. Conda only has the CPU version of it?**

ERROR: Could not find a version that satisfies the requirement torch==1.12.0+cu102 (from versions: 1.4.0, 1.4.0+cpu, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92, 1.6.0, 1.6.0+cpu, 1.6.0+cu101, 1.7.0, 1.7.0+cpu, 1.7.0+cu101, 1.7.0+cu110, 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.8.0, 1.8.0+cpu, 1.8.0+cu101, 1.8.0+cu111, 1.8.1, 1.8.1+cpu, 1.8.1+cu101, 1.8.1+cu102, 1.8.1+cu111, 1.9.0, 1.9.0+cpu, 1.9.0+cu102, 1.9.0+cu111, 1.9.1, 1.9.1+cpu, 1.9.1+cu102, 1.9.1+cu111, 1.10.0, 1.10.0+cpu, 1.10.0+cu102, 1.10.0+cu111, 1.10.0+cu113, 1.10.1, 1.10.1+cpu, 1.10.1+cu102, 1.10.1+cu111, 1.10.1+cu113, 1.10.2, 1.10.2+cpu, 1.10.2+cu102, 1.10.2+cu111, 1.10.2+cu113, 1.11.0, 1.11.0+cpu, 1.11.0+cu113, 1.11.0+cu115, 1.12.0, 1.12.0+cpu, 1.12.0+cu113, 1.12.0+cu116, 1.12.1, 1.12.1+cpu, 1.12.1+cu113, 1.12.1+cu116, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118, 2.1.0, 2.1.0+cpu, 2.1.0+cu118, 2.1.0+cu121, 2.1.1, 2.1.1+cpu, 2.1.1+cu118, 2.1.1+cu121, 2.1.2, 2.1.2+cpu, 2.1.2+cu118, 2.1.2+cu121, 2.2.0, 2.2.0+cpu, 2.2.0+cu118, 2.2.0+cu121, 2.2.1, 2.2.1+cpu, 2.2.1+cu118, 2.2.1+cu121, 2.2.2, 2.2.2+cpu, 2.2.2+cu118, 2.2.2+cu121, 2.3.0, 2.3.0+cpu, 2.3.0+cu118, 2.3.0+cu121)
ERROR: No matching distribution found for torch==1.12.0+cu102

I already have CUDA 11.8 and it works well with it. 

conda install pytorch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 pytorch-cuda=11.8 -c pytorch -c nvidia

**Comment by RuojinCai** [comment]
Hello, thanks for your question. For 1, we use the largest vocabulary trees to handle all scenes by default, but you could use different vocabulary trees depending on the number of images. For 2, thank you for sharing installation configurations with a newer version of torch.
