### ISSUE TITLE
indoor weights

### ISSUE THREAD

**Issue by awarebayes** [RuojinCai/doppelgangers#7]
Is there any chance you could provide the indoor pretrained weights?

**Comment by RuojinCai** [comment]
Thank you for your question. We have only one pretrained weight, which was trained on our proposed Doppelganger dataset. This dataset consists of internet photos of landmarks, primarily focusing on the exterior of landmarks, though it may also include a few interior photos of landmarks. While we did not specifically evaluate our model on indoor scenes, it may have the ability to generalize to such scenarios.
