### ISSUE TITLE
Runtime for the classifer

### ISSUE THREAD

**Issue by lalitmanam** [RuojinCai/doppelgangers#9]
Congratulations on the great work!

What is the expected runtime for the entire procedure of disambiguation on different sizes of datasets shown in Table 2 of the paper? 

Thank you in advance.

**Comment by RuojinCai** [comment]
Hello, thank you for your question! The entire process involves several steps: COLMAP feature extraction, COLMAP feature matching, LoFTR matching for pairs, doppelgänger classification, and COLMAP sparse reconstruction. The runtime will depend on the machine's CPU and GPU.

In general, the runtime scales with the number of images in the scene. For small scenes like Cereal (25 images), the process takes a few minutes. For medium-sized scenes like Radcliffe Camera (282 images), it takes several hours. For large scenes like Sacré-Cœur (5,450 images), the entire COLMAP + doppelgangers procedure can take several days to complete.
